services:
  postgres:
    image: postgres:16-alpine
    container_name: job_tracker_db
    environment:
      POSTGRES_DB: job_tracker
      POSTGRES_USER: job_tracker
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U job_tracker -d job_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
